/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "TcMenuDCLoad_menu.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "TcMenuDCLoad", "c1e57f0f-7446-4948-9970-833b4018e35b" };

LiquidCrystal lcd(2, 1, 0, 4, 5, 6, 7);
LiquidCrystalRenderer renderer(lcd, 20, 4);

// Global Menu Item declarations
const char enumStrSettingsSelectControl_0[] PROGMEM = "Analog";
const char enumStrSettingsSelectControl_1[] PROGMEM = "Digital";
const char* const enumStrSettingsSelectControl[] PROGMEM  = { enumStrSettingsSelectControl_0, enumStrSettingsSelectControl_1 };
const PROGMEM EnumMenuInfo minfoSettingsSelectControl = { "SelectControl", 5, 0xffff, 1, NO_CALLBACK, enumStrSettingsSelectControl };
EnumMenuItem menuSettingsSelectControl(&minfoSettingsSelectControl, 0, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnSettingsRtCall, backSubItemRenderFn, "Settings", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoSettings = { "Settings", 4, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSettings(fnSettingsRtCall, &menuSettingsSelectControl);
SubMenuItem menuSettings(&minfoSettings, &menuBackSettings, NULL);
const PROGMEM BooleanMenuInfo minfoDCLoad = { "DC Load", 3, 0xffff, 1, TogglePin13, NAMING_ON_OFF };
BooleanMenuItem menuDCLoad(&minfoDCLoad, false, &menuSettings);
RENDERING_CALLBACK_NAME_INVOKE(fnAmpsRtCall, textItemRenderFn, "Amps", -1, NO_CALLBACK)
TextMenuItem menuAmps(fnAmpsRtCall, 2, 5, &menuDCLoad);
RENDERING_CALLBACK_NAME_INVOKE(fnVoltRtCall, textItemRenderFn, "Volt", -1, NO_CALLBACK)
TextMenuItem menuVolt(fnVoltRtCall, 1, 5, &menuAmps);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).

    // Now add any readonly, non-remote and visible flags.
    menuAmps.setReadOnly(true);
    menuVolt.setReadOnly(true);

    // Code generated by plugins.
    Wire.begin();
    lcd.setIoAbstraction(ioFrom8574(0x20, 0xff, &Wire));
    lcd.begin(20, 4);
    renderer.setUpdatesPerSecond(2);
    lcd.configureBacklightPin(3);
    lcd.backlight();
    switches.initialiseInterrupt(internalDigitalIo(), true);
    menuMgr.initForEncoder(&renderer, &menuVolt, 2, 3, 8);
}

